<a href="https://colab.research.google.com/github/vanessavalis/Inteligencia_Artificial_Projeto_2/blob/main/Projeto2_IA_Kmeans_Credit_Card.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## * Instalação da biblioteca *Plotly* na versão mais recente.

In [ ]:
!pip install plotly --upgrade

## * Importações das bibliotecas *Plotly* - para geração de gráficos, *Numpy* - para manipulação de matrizes e cálculos matemáticos e *Scikit Learn* - para pré processamento de dados.

In [2]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

## * Importação do algoritmo *KMeans* a partir da biblioteca *Scikit Learn*.

In [3]:
from sklearn.cluster import KMeans

## * Importação da biblioteca *Pandas* para fazer a leitura da base de dados .xls.

In [4]:
import pandas as pd
base_cartao = pd.read_excel('/content/credit_card_clients.xls', header = 1)
base_cartao

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default payment next month
0          1      20000    2  ...         0         0                           1
1          2     120000    2  ...         0      2000                           1
2          3      90000    2  ...      1000      5000                           0
3          4      50000    2  ...      1069      1000                           0
4          5      50000    1  ...       689       679                           0
...      ...        ...  ...  ...       ...       ...                         ...
29995  29996     220000    1  ...      5000      1000                           0
29996  29997     150000    1  ...         0         0                           0
29997  29998      30000    1  ...      2000      3100                           1
29998  29999      80000    1  ...     52964      1804                           1
29999  30000      50000    1  ...      1000      1000                           1

[30000 rows x 25 columns]

## * Selecionando atributos da base de dados.

In [5]:
X_cartao_atributos = base_cartao.iloc[:, [1,12,13,14,15,16,17]].values
X_cartao_atributos

array([[ 20000,   3913,   3102, ...,      0,      0,      0],
       [120000,   2682,   1725, ...,   3272,   3455,   3261],
       [ 90000,  29239,  14027, ...,  14331,  14948,  15549],
       ...,
       [ 30000,   3565,   3356, ...,  20878,  20582,  19357],
       [ 80000,  -1645,  78379, ...,  52774,  11855,  48944],
       [ 50000,  47929,  48905, ...,  36535,  32428,  15313]])

## * Padronização de dados da base utilizando o cálculo da média e do desvio padrão.

In [6]:
scaler_cartao_atributos = StandardScaler()
X_cartao_atributos = scaler_cartao_atributos.fit_transform(X_cartao_atributos)

## * Exibição de dados padronizados.

In [7]:
X_cartao_atributos

array([[-1.13672015, -0.64250107, -0.64739923, ..., -0.67249727,
        -0.66305853, -0.65272422],
       [-0.3659805 , -0.65921875, -0.66674657, ..., -0.62163594,
        -0.60622927, -0.59796638],
       [-0.59720239, -0.29855966, -0.49389911, ..., -0.44973025,
        -0.41718767, -0.39162956],
       ...,
       [-1.05964618, -0.64722711, -0.64383044, ..., -0.34796096,
        -0.32451732, -0.32768664],
       [-0.67427636, -0.71798186,  0.41026929, ...,  0.14784373,
        -0.46806261,  0.16913036],
       [-0.90549825, -0.04473888, -0.00385085, ..., -0.10458204,
        -0.12966943, -0.39559241]])

## * Utilização do "método do cotovelo" para definição do número de clusters ideal ao problema.

In [8]:
wcss = []
for i in range (1,11):
  kmeans_cartao_atributos = KMeans(n_clusters = i, random_state = 0)
  kmeans_cartao_atributos.fit(X_cartao_atributos)
  wcss.append(kmeans_cartao_atributos.inertia_)

In [9]:
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [10]:
kmeans_cartao_atributos = KMeans (n_clusters = 4, random_state = 0)
rotulos = kmeans_cartao_atributos.fit_predict(X_cartao_atributos)

In [11]:
rotulos

array([0, 0, 0, ..., 0, 0, 0], dtype=int32)

In [12]:
from sklearn.decomposition import PCA

In [13]:
pca = PCA(n_components = 2)
X_cartao_atributos_pca = pca.fit_transform(X_cartao_atributos)

In [14]:
X_cartao_atributos_pca.shape

(30000, 2)

In [15]:
X_cartao_atributos_pca

array([[-1.76641439, -0.87620883],
       [-1.58539453, -0.12315465],
       [-1.11515565, -0.4291479 ],
       ...,
       [-1.34373768, -0.85572849],
       [-0.1119056 , -0.67790603],
       [-0.39421972, -0.86188175]])

In [16]:
grafico = px.scatter(x = X_cartao_atributos_pca[:,0], y = X_cartao_atributos_pca[:,1], color = rotulos)
grafico.show()

In [43]:
lista_clientes = np.column_stack((base_cartao, rotulos, X_cartao_atributos_pca))
lista_clientes = lista_clientes[lista_clientes[:, 25].argsort()]
lista_clientes

array([[ 1.00000000e+00,  2.00000000e+04,  2.00000000e+00, ...,
         0.00000000e+00, -1.76641439e+00, -8.76208834e-01],
       [ 1.65740000e+04,  5.00000000e+04,  1.00000000e+00, ...,
         0.00000000e+00, -3.22195550e-01, -8.86248543e-01],
       [ 1.65720000e+04,  1.00000000e+04,  1.00000000e+00, ...,
         0.00000000e+00, -1.59359181e+00, -9.79517205e-01],
       ...,
       [ 1.18400000e+03,  2.00000000e+05,  2.00000000e+00, ...,
         3.00000000e+00,  5.51528101e+00, -5.90023296e-01],
       [ 1.18200000e+03,  3.90000000e+05,  2.00000000e+00, ...,
         3.00000000e+00,  1.05701913e+01,  9.75921911e-02],
       [ 2.46600000e+04,  3.10000000e+05,  1.00000000e+00, ...,
         3.00000000e+00,  6.05732692e+00,  1.71888956e-01]])

In [46]:
import pandas as pd

tabela_clientes = pd.DataFrame(data = lista_clientes, columns=['ID', 'LIMITE', 'GÊNERO', 'EDUCAÇÃO',  'EST. CIVIL',  'IDADE',  'N. PAG. ATR. 1',  'N. PAG. ATR. 2',  'N. PAG. ATR. 3',  'N. PAG. ATR. 4',  'N. PAG. ATR. 5',  'N. PAG. ATR. 6',  'FATURA 1',  'FATURA 2',  'FATURA 3',  'FATURA 4',  'FATURA 5',  'FATURA 6',  'PAGAMENTO 1',  'PAGAMENTO 2',  'PAGAMENTO 3',  'PAGAMENTO 4',  'PAGAMENTO 5',  'PAGAMENTO 6', 'PAG. PROX. MES', 'CLASSIFICAÇÃO', 'X', 'Y'])
tabela_clientes.head()

ID   LIMITE  GÊNERO  ...  CLASSIFICAÇÃO         X         Y
0      1.0  20000.0     2.0  ...            0.0 -1.766414 -0.876209
1  16574.0  50000.0     1.0  ...            0.0 -0.322196 -0.886249
2  16572.0  10000.0     1.0  ...            0.0 -1.593592 -0.979517
3  16571.0  20000.0     1.0  ...            0.0 -1.712338 -0.885197
4  16570.0  50000.0     1.0  ...            0.0 -0.070732 -0.900587

[5 rows x 28 columns]

In [47]:
tabela_clientes.to_excel('tabela_clientes.xls')

In [48]:
import pandas as pd
tabela_clientes = pd.read_excel('/content/tabela_clientes.xls')
tabela_clientes

Unnamed: 0     ID  LIMITE  ...  CLASSIFICAÇÃO          X         Y
0               0      1   20000  ...              0  -1.766414 -0.876209
1               1  16574   50000  ...              0  -0.322196 -0.886249
2               2  16572   10000  ...              0  -1.593592 -0.979517
3               3  16571   20000  ...              0  -1.712338 -0.885197
4               4  16570   50000  ...              0  -0.070732 -0.900587
...           ...    ...     ...  ...            ...        ...       ...
29995       29995  20190  310000  ...              3   6.516480  0.121157
29996       29996  25534  300000  ...              3   8.380856 -0.239954
29997       29997   1184  200000  ...              3   5.515281 -0.590023
29998       29998   1182  390000  ...              3  10.570191  0.097592
29999       29999  24660  310000  ...              3   6.057327  0.171889

[30000 rows x 29 columns]