<a href="https://colab.research.google.com/github/vanessavalis/Inteligencia_Artificial_Projeto_2/blob/main/Projeto2_IA_Kmeans_Credit_Card.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## * Instalação da biblioteca *Plotly* na versão mais recente.

In [ ]:
!pip install plotly --upgrade

## * Importações das bibliotecas *Plotly* - para geração de gráficos, *Numpy* - para manipulação de matrizes e cálculos matemáticos e *Scikit Learn* - para pré processamento de dados.

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

## * Importação do algoritmo *KMeans* a partir da biblioteca *Scikit Learn*.

In [ ]:
from sklearn.cluster import KMeans

## * Importação da biblioteca *Pandas* para fazer a leitura da base de dados .xls.

In [ ]:
import pandas as pd
base_cartao = pd.read_excel('/content/credit_card_clients.xls', header = 1)
base_cartao

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default payment next month
0          1      20000    2  ...         0         0                           1
1          2     120000    2  ...         0      2000                           1
2          3      90000    2  ...      1000      5000                           0
3          4      50000    2  ...      1069      1000                           0
4          5      50000    1  ...       689       679                           0
...      ...        ...  ...  ...       ...       ...                         ...
29995  29996     220000    1  ...      5000      1000                           0
29996  29997     150000    1  ...         0         0                           0
29997  29998      30000    1  ...      2000      3100                           1
29998  29999      80000    1  ...     52964      1804                           1
29999  30000      50000    1  ...      1000      1000                           1

[30000 rows x 25 columns]

## * Selecionando atributos da base de dados.

In [ ]:
X_cartao_atributos = base_cartao.iloc[:, [2,13,14,15,16,17,18,19,20,21,22,23,24]].values
X_cartao_atributos

array([[    2,  3102,   689, ...,     0,     0,     1],
       [    2,  1725,  2682, ...,     0,  2000,     1],
       [    2, 14027, 13559, ...,  1000,  5000,     0],
       ...,
       [    1,  3356,  2758, ...,  2000,  3100,     1],
       [    1, 78379, 76304, ..., 52964,  1804,     1],
       [    1, 48905, 49764, ...,  1000,  1000,     1]])

## * Padronização de dados da base utilizando o cálculo da média e do desvio padrão.

In [ ]:
scaler_cartao_atributos = StandardScaler()
X_cartao_atributos = scaler_cartao_atributos.fit_transform(X_cartao_atributos)

## * Exibição de dados padronizados.

In [ ]:
X_cartao_atributos

array([[ 0.81016074, -0.64739923, -0.66799331, ..., -0.31413612,
        -0.29338206,  1.87637834],
       [ 0.81016074, -0.66674657, -0.63925429, ..., -0.31413612,
        -0.18087821,  1.87637834],
       [ 0.81016074, -0.49389911, -0.48240819, ..., -0.24868274,
        -0.01212243, -0.53294156],
       ...,
       [-1.23432296, -0.64383044, -0.63815838, ..., -0.18322937,
        -0.11900109,  1.87637834],
       [-1.23432296,  0.41026929,  0.42237335, ...,  3.15253642,
        -0.19190359,  1.87637834],
       [-1.23432296, -0.00385085,  0.03966713, ..., -0.24868274,
        -0.23713013,  1.87637834]])

## * Utilização do "método do cotovelo" para definição do número de clusters ideal ao problema.

In [ ]:
wcss = []
for i in range (1,11):
  kmeans_cartao_atributos = KMeans(n_clusters = i, random_state = 0)
  kmeans_cartao_atributos.fit(X_cartao_atributos)
  wcss.append(kmeans_cartao_atributos.inertia_)

In [ ]:
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [ ]:
kmeans_cartao_atributos = KMeans (n_clusters = 4, random_state = 0)
rotulos = kmeans_cartao_atributos.fit_predict(X_cartao_atributos)

In [ ]:
rotulos

array([2, 2, 0, ..., 2, 2, 2], dtype=int32)

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components = 2)
X_cartao_atributos_pca = pca.fit_transform(X_cartao_atributos)

In [ ]:
X_cartao_atributos_pca.shape

(30000, 2)

In [ ]:
X_cartao_atributos_pca

array([[-1.67861964, -0.53222242],
       [-1.5736166 , -0.46569592],
       [-1.10853573,  0.02935716],
       ...,
       [-0.96562413, -0.05149611],
       [ 1.34785519,  2.07481765],
       [-0.45258144, -0.84877831]])

In [ ]:
grafico = px.scatter(x = X_cartao_atributos_pca[:,0], y = X_cartao_atributos_pca[:,1], color = rotulos)
grafico.show()

In [ ]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes = lista_clientes[lista_clientes[:, 25].argsort()]
lista_clientes

array([[ 15000,  50000,      1, ...,   1616,      0,      0],
       [ 15027, 150000,      1, ...,  25069,      0,      0],
       [ 15026,  80000,      1, ...,   1503,      0,      0],
       ...,
       [ 18647, 390000,      2, ...,   6600,      0,      3],
       [  6166, 360000,      2, ...,   9973,      0,      3],
       [  6767, 220000,      2, ...,   8621,      0,      3]])

In [ ]:
with open("clientes.txt", "w") as arquivo:
    for valor in lista_clientes:
      arquivo.write(str(valor) + '\n')

In [ ]:
with open("clientes.txt", "r") as arquivo:
    for valor in lista_clientes:
      print(valor)