<a href="https://colab.research.google.com/github/vanessavalis/Inteligencia_Artificial_Projeto_2/blob/main/Projeto2_IA_Kmeans_Credit_Card.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## * Instalação da biblioteca *Plotly* na versão mais recente.

In [1]:
!pip install plotly --upgrade

     |████████████████████████████████| 23.9 MB 13 kB/s 
  Attempting uninstall: plotly
    Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1


## * Importações das bibliotecas *Plotly* - para geração de gráficos, *Numpy* - para manipulação de matrizes e cálculos matemáticos e *Scikit Learn* - para pré processamento de dados.

In [2]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

## * Importação do algoritmo *KMeans* a partir da biblioteca *Scikit Learn*.

In [3]:
from sklearn.cluster import KMeans

## * Importação da biblioteca *Pandas* para fazer a leitura da base de dados .xls.

In [5]:
import pandas as pd
base_cartao = pd.read_excel('/content/credit_card_clients.xls', header = 1)
base_cartao

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default payment next month
0          1      20000    2  ...         0         0                           1
1          2     120000    2  ...         0      2000                           1
2          3      90000    2  ...      1000      5000                           0
3          4      50000    2  ...      1069      1000                           0
4          5      50000    1  ...       689       679                           0
...      ...        ...  ...  ...       ...       ...                         ...
29995  29996     220000    1  ...      5000      1000                           0
29996  29997     150000    1  ...         0         0                           0
29997  29998      30000    1  ...      2000      3100                           1
29998  29999      80000    1  ...     52964      1804                           1
29999  30000      50000    1  ...      1000      1000                           1

[30000 rows x 25 columns]

## * Selecionando atributos da base de dados.

In [7]:
X_cartao_atributos = base_cartao.iloc[:, 1:24].values
X_cartao_atributos

array([[ 20000,      2,      2, ...,      0,      0,      0],
       [120000,      2,      2, ...,   1000,      0,   2000],
       [ 90000,      2,      2, ...,   1000,   1000,   5000],
       ...,
       [ 30000,      1,      2, ...,   4200,   2000,   3100],
       [ 80000,      1,      3, ...,   1926,  52964,   1804],
       [ 50000,      1,      2, ...,   1000,   1000,   1000]])

## * Padronização de dados da base utilizando o cálculo da média e do desvio padrão.

In [12]:
scaler_cartao_atributos = StandardScaler()
X_cartao_atributos = scaler_cartao_atributos.fit_transform(X_cartao_atributos)

## * Exibição de dados padronizados.

In [14]:
X_cartao_atributos

array([[-1.13672015,  0.81016074,  0.18582826, ..., -0.30806256,
        -0.31413612, -0.29338206],
       [-0.3659805 ,  0.81016074,  0.18582826, ..., -0.24422965,
        -0.31413612, -0.18087821],
       [-0.59720239,  0.81016074,  0.18582826, ..., -0.24422965,
        -0.24868274, -0.01212243],
       ...,
       [-1.05964618, -1.23432296,  0.18582826, ..., -0.03996431,
        -0.18322937, -0.11900109],
       [-0.67427636, -1.23432296,  1.45111372, ..., -0.18512036,
         3.15253642, -0.19190359],
       [-0.90549825, -1.23432296,  0.18582826, ..., -0.24422965,
        -0.24868274, -0.23713013]])

## * Utilização do "método do cotovelo" para definição do número de clusters ideal ao problema.

In [15]:
wcss = []
for i in range (1,11):
  kmeans_cartao_atributos = KMeans(n_clusters = i, random_state = 0)
  kmeans_cartao_atributos.fit(X_cartao_atributos)
  wcss.append(kmeans_cartao_atributos.inertia_)

In [16]:
grafico = px.line(x = range(1,11), y = wcss)
grafico.show()

In [17]:
kmeans_cartao_atributos = KMeans (n_clusters = 6, random_state = 0)
rotulos = kmeans_cartao_atributos.fit_predict(X_cartao_atributos)

In [18]:
rotulos

array([2, 2, 2, ..., 1, 2, 2], dtype=int32)

In [19]:
from sklearn.decomposition import PCA

In [20]:
pca = PCA(n_components = 2)
X_cartao_atributos_pca = pca.fit_transform(X_cartao_atributos)

In [21]:
X_cartao_atributos_pca.shape

(30000, 2)

In [22]:
X_cartao_atributos_pca

array([[-1.88796284, -0.906103  ],
       [-0.76469564, -2.10928929],
       [-0.84740788, -1.07217936],
       ...,
       [ 0.35745676, -3.31274715],
       [ 0.65055225,  0.7228957 ],
       [-0.14556432, -0.8097527 ]])

In [23]:
grafico = px.scatter(x = X_cartao_atributos_pca[:,0], y = X_cartao_atributos_pca[:,1], color = rotulos)
grafico.show()

In [28]:
lista_clientes = np.column_stack((base_cartao, rotulos))
lista_clientes = lista_clientes[lista_clientes[:, 1:24].argsort()]
lista_clientes

array([[[    11, 200000,      2, ...,     66,      0,      2],
        [    10,  20000,      1, ...,      0,      0,      5],
        [     8, 100000,      2, ...,   1542,      0,      2],
        ...,
        [    13, 630000,      2, ...,      0,      0,      5],
        [    12, 260000,      2, ...,   3640,      0,      5],
        [     1,  20000,      2, ...,      0,      1,      2]],

       [[     6,  50000,      1, ...,    800,      0,      2],
        [     9, 140000,      2, ...,   1000,      0,      2],
        [    22, 120000,      2, ...,      0,      1,      5],
        ...,
        [    15, 250000,      1, ...,   3000,      0,      2],
        [    16,  50000,      2, ...,   1100,      0,      2],
        [     1,  20000,      2, ...,      0,      1,      2]],

       [[    11, 200000,      2, ...,     66,      0,      2],
        [     6,  50000,      1, ...,    800,      0,      2],
        [     7, 500000,      1, ...,  13770,      0,      3],
        ...,
        [   